#!/bin/bash
#
# NAME
#       searchtobibtex
#
# SYNOPSIS
#       searchtobibtex [options] search_string
#
# DESCRIPTION
#       performs crossref search and uses DOI to pull bibtex
#       see e.g. http://labs.crossref.org/resolving-citations-we-dont-need-no-stinkin-parser/
#
# OPTIONS
#       -r NUM      Return only NUM results (default 1)
#       -y YEAR     Restrict results to year=YEAR
#
# COMMENTS
#       Requires bibclean and bibtool, which are distributed as part of texlive distribution. Also requires doitobibtex
#
# COPYRIGHT
#       Copyright (C) 2015 Ati Sharma
#
#       This program is free software: you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation, either version 3 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program.  If not, see <http://www.gnu.org/licenses/>.


# parse command line args
while getopts y:r: opt; do
    case $opt in
        y)
            YEAR=$OPTARG
            ;;
        r)
            RESULTS=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

# remaining arguments assumed to be search terms
TERMS=$@

# bibtool key format string
BIBKEYFMT='%3n(author)%+4d($year)'
# All the things that you don't want in your bibtex entry, separated by \|
BIBENTRYFILTER='= ,\|\"-\"\|url'

# construct the freeform search, results sorted by score
QUERYURL=$(echo "http://search.crossref.org/dois?sort=score&q=$TERMS&year=$YEAR" | sed 's/ /+/g')

# extract the DOI
# DOI is already in URL form
# default to 1 result
DOI=$(grep -m ${RESULTS:-1} "http://dx.doi.org" <(curl -s "$QUERYURL") | cut -d\" -f4)

for URL in $DOI; do
    doitobibtex $URL
done
