#!/bin/bash
#
# Copyright (C) 2015 Ati Sharma
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# default bibtool key format string
BIBKEYFMT='%3n(author):%+4d(year)'

# parse command line args
while getopts y:r: opt; do
    case $opt in
        y)
            YEAR=$OPTARG
            ;;
        r)
            RESULTS=$OPTARG
            ;;
        f)
            BIBKEYFMT=$OPTARG
            ;;
    esac
done

shift $((OPTIND - 1))

# remaining arguments assumed to be search terms
TERMS=$@

# All the things that you don't want in your bibtex entry, separated by \|
BIBENTRYFILTER='= ,\|\"-\"\|url'

# construct the freeform search, results sorted by score
QUERYURL=$(echo "http://search.crossref.org/dois?sort=score&q=$TERMS&year=$YEAR" | sed 's/ /+/g')

# extract the DOI
# DOI is already in URL form
# default to 1 result
DOI=$(grep -m ${RESULTS:-1} "http://dx.doi.org" <(curl -s "$QUERYURL") | cut -d\" -f4)

for URL in $DOI; do
    # This code is duplicated from doitobibtex. I justify the copypasta as reducing dependencies.
    # uses crossref API
    # see http://www.crossref.org/CrossTech/2011/11/turning_dois_into_formatted_ci.html
    # resolve URL
    curl -s -LH "Accept: text/bibliography; style=bibtex" $URL | sed 's/,/,\n/g' | sed 's/}}/}\n}/' | grep -v "$BIBENTRYFILTER" | bibclean -delete-empty-values -no-check-values | bibtool -F -f "$BIBKEYFMT";
done
